travis:
  secure:
    BINSTAR_TOKEN: pq6zK6+eTOcYApmK1fy3kAloc4LagqXDy19tV1GjD95b5GFzIb51cgUjG4RFmHgNMBQnkrFEoJsY1NHj0M5FlsaXfzavxOfUXLnSVmMJ3Wdl3buZCnPT5W9IEoGiSNYaHwyk93tWUY3xVKAzyZnwAZomzxDB72hQajRWykEmSCpR1L6Kzzx6EGP3H5AjExf/MzqytKYj7270xR5UqPgPtpFrvNO/u+oXk5/3MK9KU+bNsaSwRKAcFf7myd2km9SIRg0cZ5hsyimgoWiZ6R32oR9/YoFNfRgVTA68KQFyCA36td6KC0S14fzbp990/pdd0TDph52C0tbpaqp3hvRx84dFu1UEl2XupIIIeAfT8yuRhV63U2WfPmkymXo3+m/IFU+Ns7fR3MloeDRSnuO2MQjhoqtv9dTJ8Zeuguaa3E1ZHs3IclRKTBcka7SHMSVmEF3s9HOqCusIJR/34nDE4E+WnQeNViHyaf6wYCZ3MkrY8/2v9PbN5fdP262wlboB5Dhzn6kl1AFoTsXTUIx2UvL+9ivmSIPkBBRjyGZ3fw+9vW3FTHGusLDXcJ4VM2DGmwkm66gWB+ZcZ932+foXrBE/ijKMeYXTAJ/8x+h3pexLWal6CRa7XjTJZ2kWyijIGrVJzJ2ft7nl+ySKPKKRyRieJ0nCoJ/Lar5g4m3xDoU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
